// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbPcDAgnUY3cFAlON3M5hkB4XfLJmUDrw',
    appId: '1:541625264570:android:1a4a6c3b71d4c105809583',
    messagingSenderId: '541625264570',
    projectId: 'thingsonwheels-751ca',
    storageBucket: 'thingsonwheels-751ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtjOj7y19IlVetiWXeH1E4an8FsjbQ6U',
    appId: '1:541625264570:ios:6c2027a491bfb7a6809583',
    messagingSenderId: '541625264570',
    projectId: 'thingsonwheels-751ca',
    storageBucket: 'thingsonwheels-751ca.appspot.com',
    androidClientId: '541625264570-33gd8rhofsopuqlqekmu0qfkqbdko7p8.apps.googleusercontent.com',
    iosClientId: '541625264570-3nmjvv79aio8sf2k2bd4eitah99ms2ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsonwheels',
  );
}
